### ISSUE TITLE
Issues with data types having more than 3 constructors

### ISSUE THREAD

**Issue by adarqui** [Gabriel439/Haskell-Optparse-Generic-Library#12] opened 2016-03-09 07:50 UTC
Hi Gabriel,

I've run into some weird issues when testing out your library. The following code works:

```
{-# LANGUAGE DeriveGeneric     #-}
{-# LANGUAGE OverloadedStrings #-}

import           Options.Generic
import           Data.Text (Text)

data CliCommands
  = ACmd Text
  | BCmd Text
  | CCmd Text
  deriving (Show, Generic)

instance ParseRecord CliCommands

main = do
  x <- getRecord "Triggers CLI"
  print (x :: CliCommands)
```

However, adding one more constructor seems to cause a fatal error:

```
{-# LANGUAGE DeriveGeneric     #-}
{-# LANGUAGE OverloadedStrings #-}

import           Options.Generic
import           Data.Text (Text)

data CliCommands
  = ACmd Text
  | BCmd Text
  | CCmd Text
  | DCmd Text
  deriving (Show, Generic)

instance ParseRecord CliCommands

main = do
  x <- getRecord "Triggers CLI"
  print (x :: CliCommands)
```

Error message:

```
Main.hs:16:10:
    No instance for (Options.Generic.GenericParseRecord
                       ((GHC.Generics.C1
                           Main.C1_0CliCommands
                           (GHC.Generics.S1 GHC.Generics.NoSelector (GHC.Generics.Rec0 Text))
                         GHC.Generics.:+: GHC.Generics.C1
                                            Main.C1_1CliCommands
                                            (GHC.Generics.S1
                                               GHC.Generics.NoSelector (GHC.Generics.Rec0 Text)))
                        GHC.Generics.:+: (GHC.Generics.C1
                                            Main.C1_2CliCommands
                                            (GHC.Generics.S1
                                               GHC.Generics.NoSelector (GHC.Generics.Rec0 Text))
                                          GHC.Generics.:+: GHC.Generics.C1
                                                             Main.C1_3CliCommands
                                                             (GHC.Generics.S1
                                                                GHC.Generics.NoSelector
                                                                (GHC.Generics.Rec0 Text)))))
    arising from a use of ‘Options.Generic.$gdmparseRecord’
    In the expression: Options.Generic.$gdmparseRecord
    In an equation for ‘parseRecord’:
        parseRecord = Options.Generic.$gdmparseRecord
    In the instance declaration for ‘ParseRecord CliCommands’
```

I've tested a few different things and it seems simply to be related to the constructor count being > 3.

If this is just something i'm doing wrong, sorry for the misunderstanding.

Thanks!

**Comment by adarqui** [comment] 2016-03-09 07:59
Also when I compile the first example with 3 constructors, it hangs indefinitely.. Works fine with 2 constructors.

I'm using ghc 7.10.3 on Mac OS X.

**Comment by h3st** [comment] 2016-03-09 12:24
looks like a dupe of #9

**Comment by adarqui** [comment] 2016-03-09 17:57
I will close this one. I didn't notice the non-termination behavior until after I posted this.

Thanks!

**Closed as completed** 2016-03-09 17:57 UTC
